@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.karelmikie3.craftcord.resources;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;